FROM sequenceiq/hadoop-docker:2.7.1
MAINTAINER SequenceIQ

#support for Hadoop 2.7.1
RUN yum install -y java-1.8.0-openjdk
ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0-openjdk.x86_64
ENV PATH $PATH:$JAVA_HOME/bin
RUN curl -s http://d3kbcqa49mib13.cloudfront.net/spark-2.2.0-bin-hadoop2.7.tgz | tar -xz -C /usr/local/
RUN cd /usr/local && ln -s spark-2.2.0-bin-hadoop2.7 spark
ENV SPARK_HOME /usr/local/spark
RUN mkdir $SPARK_HOME/yarn-remote-client
ADD yarn-remote-client $SPARK_HOME/yarn-remote-client

RUN ls $SPARK_HOME-2.2.0-bin-hadoop2.7/
RUN mkdir /opt/yelp
COPY yelp_dataset_challenge_round9.tar .
RUN tar -xzvf yelp_dataset_challenge_round9.tar -C /opt/yelp/
COPY test-1.2.jar /opt/yelp
RUN export HADOOP_USER_NAME=root

RUN $BOOTSTRAP && $HADOOP_PREFIX/bin/hadoop dfsadmin -safemode leave && $HADOOP_PREFIX/bin/hdfs dfs -put $SPARK_HOME-2.2.0-bin-hadoop2.7/jars /spark && $HADOOP_PREFIX/bin/hdfs dfs -mkdir /opt && $HADOOP_PREFIX/bin/hdfs dfs -mkdir /opt/yelp && $HADOOP_PREFIX/bin/hdfs dfs -put /opt/yelp/* /opt/yelp/
COPY hadoop-env.sh $HADOOP_PREFIX/etc/hadoop
ENV YARN_CONF_DIR $HADOOP_PREFIX/etc/hadoop
ENV PATH $PATH:$SPARK_HOME/bin:$HADOOP_PREFIX/bin
# update boot script
COPY bootstrap.sh /etc/bootstrap.sh
RUN chown root.root /etc/bootstrap.sh
RUN chmod 700 /etc/bootstrap.sh

#install R
RUN rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
RUN yum -y install R

ENTRYPOINT ["/etc/bootstrap.sh"]
